CREATE TABLE users (
    userID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL,
    pass VARCHAR(280) NOT NULL,
    fname VARCHAR(50) NOT NULL,
    mname VARCHAR(1) DEFAULT NULL,
    lname VARCHAR(50) NOT NULL,
    icon VARCHAR(260) NULL DEFAULT '',
    permission VARCHAR(15) NOT NULL DEFAULT 'member',
    ip VARCHAR(15) NOT NULL,
    accCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    OnlineStat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isOnline TINYINT(1) DEFAULT 0,
    public_key VARCHAR(300) NOT NULL DEFAULT ''
);

CREATE TABLE pages (
    pageID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pageName VARCHAR(100) NOT NULL UNIQUE,
    pageIcon VARCHAR(150) NOT NULL,
    pageDraft VARCHAR(260) NOT NULL DEFAULT '/drafts/',
    pageCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    pageEdited TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE forums (
    forumID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    forumName VARCHAR(70) NOT NULL UNIQUE,
    forumAuthor VARCHAR(50) NOT NULL,
    forumCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    forumEdited TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    forumColor VARCHAR(11) NOT NULL DEFAULT 'transparent',
    forumIcon VARCHAR(150) NULL DEFAULT ''
);

CREATE TABLE topics (
    topicID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    topicName VARCHAR(120) NOT NULL UNIQUE,
    topicAuthor VARCHAR(50) NOT NULL,
    topicMsg TEXT NOT NULL,
    topicCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    topicEdited TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    forumID INT NOT NULL,
    FOREIGN KEY (forumID) REFERENCES forums(forumID) ON DELETE CASCADE
);

CREATE TABLE replies (
    replyID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    replyAuthor VARCHAR(50) NOT NULL,
    replyMsg TEXT NOT NULL,
    replyCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    replyEdited TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    topicID INT NOT NULL,
    FOREIGN KEY (topicID) REFERENCES topics(topicID) ON DELETE CASCADE
);

CREATE TABLE logger(
    eventID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    eventType VARCHAR(150) NOT NULL,
    eventDescription TEXT NOT NULL,
    eventStatus ENUM('success', 'failure') NOT NULL,
    eventTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE plugins (
    pluginID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pluginName VARCHAR(100) NOT NULL UNIQUE,
    pluginStatus TINYINT(1) DEFAULT 0,
    pluginDisable TINYINT(1) DEFAULT 0
);

CREATE TABLE config (
    configID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL DEFAULT 'NetWorks',
    lang VARCHAR(60) NOT NULL DEFAULT 'en-us',
    theme VARCHAR(50) NOT NULL DEFAULT 'default',
    debug TINYINT(1) DEFAULT 1,
    editor VARCHAR(50) NOT NULL DEFAULT 'md',
    dFormat VARCHAR(120) NOT NULL DEFAULT 'F d, Y h:ia',
    ico16 VARCHAR(260) DEFAULT '',
    ico24 VARCHAR(260) DEFAULT '',
    ico32 VARCHAR(260) DEFAULT '',
    ico48 VARCHAR(260) DEFAULT '',
    ico64 VARCHAR(260) DEFAULT '',
    ico96 VARCHAR(260) DEFAULT '',
    ico128 VARCHAR(260) DEFAULT '',
    ico256 VARCHAR(260) DEFAULT '',
    ico512 VARCHAR(260) DEFAULT '',
    siteDescription TEXT DEFAULT '',
    author VARCHAR(50) DEFAULT '',
    refresh INT DEFAULT 0,
    keywords VARCHAR(255) DEFAULT '',
    botIndex TINYINT(1) DEFAULT 0,
    botLink TINYINT(1) DEFAULT 0,
    rating VARCHAR(45) DEFAULT NULL,
    copyright VARCHAR(50) DEFAULT NULL,
    distribute VARCHAR(55) DEFAULT 'global',
    revist INT DEFAULT 7,
    charset VARCHAR(120) NOT NULL DEFAULT 'UTF-8',
    timezone VARCHAR(150) NOT NULL DEFAULT 'Europe/Berlin',
    secure VARCHAR(10) NOT NULL DEFAULT 'moderate'
);

CREATE TABLE recaptcha(
    reCAPTCHA_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    reCAPTCHA_active TINYINT(1) DEFAULT 0,
    reCAPTCHA_version VARCHAR(2) NOT NULL,
    reCAPTCHA_type VARCHAR(150) NULL DEFAULT 'checkbox',
    reCAPTCHA_siteKey VARCHAR(40) NOT NULL,
    reCAPTCHA_secretKey TEXT NOT NULL
);

CREATE TABLE mail (
    mailID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mail_from VARCHAR(256) NOT NULL,
    mail_to VARCHAR(256) NOT NULL,
    mail_cc VARCHAR(256) DEFAULT NULL,
    mail_bcc VARCHAR(256) DEFAULT NULL,
    mail_subject VARCHAR(200) NOT NULL,
    mail_msg TEXT NOT NULL,
    UNIQUE (mail_from, mail_subject)
);

CREATE TABLE mail_replies (
    mail_replyID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mail_subject VARCHAR(200) NOT NULL,
    mail_from VARCHAR(256) NOT NULL,
    mail_to VARCHAR(256) NOT NULL,
    msg TEXT NOT NULL,
    UNIQUE (mail_from, mail_subject)
);

CREATE TABLE mail_forward (
    mail_forwardID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mail_subject VARCHAR(200) NOT NULL,
    mail_from VARCHAR(256) NOT NULL,
    mail_to VARCHAR(256) NOT NULL
);